### ISSUE TITLE
inspect a table lost some data

### ISSUE THREAD

**Issue by formula123** [kikito/inspect.lua#24]
I use inspect print a table,but some data lost. for example.
```lua
inspect = require("inspect")
cjson = require("cjson")
tb = {[2]=28,[3]=1,[4]=90,sid=99,[13]=2,[26]=1,iid=1,[25]=1006}
--use pairs to print
for k, v in pairs(tb) do
    print(k,v)
end
--result:
--2       28
--3       1
--4       90
--sid     99
--13      2
--26      1
--iid     1
--25      1006
--use inspect
print(inspect(tb))
--result:
--{ nil, 28, 1, 90,
--  [13] = 2,
--  [25] = 1006,
--  [26] = 1,
--  iid = 1,
--  sid = 99
--}
--use cjson to print
print(csjon.encode(tb))
--result:
--{"2":28,"3":1,"4":90,"sid":99,"13":2,"26":1,"iid":1,"25":1006}
--use cjson encode,decode will be fine
print(inspect(cjson.decode(cjson.encode(tb))))
--result:
--{
--     ["13"] = 2,
--     ["2"] = 28,
--     ["25"] = 1006,
--     ["26"] = 1,
--     ["3"] = 1,
--     ["4"] = 90,
--     iid = 1,
--     sid = 99
--}
```
Any idea to solve data lost?

**Comment by kikito** [comment]
Hi there,

There are several problems here. One of them is that you might indeed have found a bug in inspect. But even if I solve that bug, the result might still not be what you want. Let me explain.

`inspect` renders "array-like" tables like arrays. It renders `{4,5,6}` instead of `{[1]=4,[2]=5,[3]=6}` (with some newlines & spaces between them)

It also renders the "struct-like" tables using one line per key, showing the keys, etc, like your json example does.

The tables which are "hybrid" (part array and part struct) are shown "hybrid": array part first and struct part later. So if you have `{4,5,6,foo=7}`, it renders it like you are seeing now:

``` lua
{ 4, 5, 6,
  foo = 7
}
```

The bug is that the table that you have given me in your example should not have been identified as "having an array part". Because the item in `1` is nil. I will definitively fix that.

On the other hand, if you have other case where you have a `1` in your keys, you will still see that identified as an "array", and printed out with "missing information" (which is not really missing, just expressed in a different way).

While I am doing this fix, there is a short-term solution you could use: you could make all your table keys strings instead of numbers. So instead of

``` lua
tb = {[2]=28,[3]=1,[4]=90,sid=99,[13]=2,[26]=1,iid=1,[25]=1006}
```
You would have this:
``` lua
tb = {['2']=28,['3']=1,['4']=90,sid=99,['13']=2,['26']=1,iid=1,['25']=1006}
```
That will correctly identify the table as a struct-like table and print it "the struct way".

I will also consider disabling "hybrid table printout" - so if one non-array value is detected, the tables are always printed as "structs". We will see.

**Comment by formula123** [comment]
ok,I will take your advice !

**Comment by kikito** [comment]
Hi there, I have fixed the issue and released a new version of inspect.lua. It will works as expected with the example you told me before:

``` lua
> print(inspect({[2]=28,[3]=1,[4]=90,sid=99,[13]=2,[26]=1,iid=1,[25]=1006}))
{
  [2] = 28,
  [3] = 1,
  [4] = 90,
  [13] = 2,
  [25] = 1006,
  [26] = 1,
  iid = 1,
  sid = 99
}
```

But it will still print it as an "array" if there is a number 1 as key:

```
> print(inspect({[1]='foo',[2]=28,[3]=1,[4]=90,sid=99,[13]=2,[26]=1,iid=1,[25]=1006}))
{ "foo", 28, 1, 90,
  [13] = 2,
  [25] = 1006,
  [26] = 1,
  iid = 1,
  sid = 99
}
```

So you might want to stick to using strings instead of numbers. That way you will not have unexpected output.

Regards!
