### ISSUE TITLE
Error: attempt to compare number with nil

### ISSUE THREAD

**Issue by doronbehar** [kikito/inspect.lua#44]
I'm trying to debug my Pandoc Lua filter and I get this error when I'm trying to inspect certain objects:

```
Error running filter filter.lua:
/home/doron/.luarocks/share/lua/5.3/inspect.lua:246: attempt to compare number with nil
stack traceback:
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:246: in method 'putTable'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:303: in method 'putValue'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:263: in local 'f'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:208: in method 'down'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:253: in method 'putTable'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:303: in method 'putValue'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:263: in local 'f'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:208: in method 'down'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:253: in method 'putTable'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:303: in method 'putValue'
	...
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:303: in method 'putValue'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:263: in local 'f'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:208: in method 'down'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:253: in method 'putTable'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:303: in method 'putValue'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:272: in local 'f'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:208: in method 'down'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:253: in method 'putTable'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:303: in method 'putValue'
	/home/doron/.luarocks/share/lua/5.3/inspect.lua:334: in function 'inspect.inspect'
	(...tail calls...)
	[string "filter.lua"]:5: in function 'Pandoc'
```

And the Lua filter is:

```lua
inspect = require('inspect')

function Pandoc(doc)
	log = io.open("filter.log", "w")
	log:write(inspect(doc))
	log:close()
end
```

EDIT: Documentation for Pandoc Lua filters - https://pandoc.org/lua-filters.html

**Comment by turbo** [comment]
Same issue here. I don't actually know what the underlying data is, hence why I try to dump it with Inspect, but it runs into this error.

**Comment by doronbehar** [comment]
I use https://stevedonovan.github.io/Penlight/api/libraries/pl.pretty.html now.

**Comment by kikito** [comment]
I didn't even notice this issue was open, apologies for that.

line 246 in a current version of inspect does not do any numeric comparison, it's possible that this issue is just a matter of updating to the latest version

My next best guess is: the closest line to 246 which does a numeric comparison is `if self.tableAppearances[t] > 1 then self:puts('<', self:getId(t), '>') end`. That throwing a `nil` would imply that there is a bug on the pre-parsing of tables, or that there are tables that are somehow "visitable" only the second time we iterate over them. I would need some sample data in order to replicate this, otherwise it's impossible. I can't commit my time to installing Pandoc and trying there.

For now I will close the issue. If new data arises, please reopen.
