### ISSUE TITLE
Use dofile in Gideros

### ISSUE THREAD

**Issue by scrumit** [kikito/inspect.lua#51]
I couldn't use require in Gideros. 

This works:

> local inspect = dofile("inspect.lua")

At the moment I'm just investigating the structure of some generated tables, but I can see this is a valuable tool for validation. So I'm not going to create a PR, just in case there are other differences.

**Comment by kikito** [comment]
I am not an expert in Gideros, but it seems that in order to be able to use `require` on it you must "create a Gideros plugin" first. That seems to be the recommended way for using libraries in projects.

See this doc: https://wiki.giderosmobile.com/index.php/Making_a_Plugin

Once you have created the plugin following the steps there, you should be able to drop inspect.lua inside the plugin folder and use it regularly, with `require`
